"""empty message

Revision ID: 464e308b7a8f
Revises: 597cf160ab1
Create Date: 2017-04-18 20:29:26.191554

"""

# revision identifiers, used by Alembic.
revision = '464e308b7a8f'
down_revision = '597cf160ab1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('push_token', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'push_token')
    ### end Alembic commands ###
