"""empty message

Revision ID: 53ec14df8885
Revises: 13e6c5ef27c3
Create Date: 2017-03-22 12:31:33.994209

"""

# revision identifiers, used by Alembic.
revision = '53ec14df8885'
down_revision = '13e6c5ef27c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
